name: NgxFlexMessages Main 
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12.x'
          registry-url: 'https://registry.npmjs.org'

      - name: "Generate unique id"
        id: generate_unique_id
        uses: ./.github/actions/build_id

      - name: Install application
        run: npm install

      - name: Deploy application
        run: npm run publish:canary
        env:
          BUILD_ID: ${{ steps.generate_unique_id.outputs.unique_id }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}