name: NgxFlexMessages Release 
on:
  push:
    branches:
      - release
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Setup GIT user
        uses: fregante/setup-git-user@v1

      - name: "Generate unique id"
        id: generate_unique_id
        uses: ./.github/actions/build_id

      - name: Install application
        run: npm install

      - name: Release application
        if:  false == contains('skip-deploy', ${{ github.event.head_commit.message }})
        run: npm run publish:release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          BUILD_ID: ${{ steps.generate_unique_id.outputs.unique_id }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}